package com.haselton.hmgaibeatgenerator

import android.content.ContentValues
import android.media.*
import android.os.Bundle
import android.provider.MediaStore
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import java.io.OutputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.concurrent.thread
import kotlin.math.*

class MainActivity:AppCompatActivity(){
 private var track:AudioTrack?=null;private var pcm:ShortArray?=null;private var promptName="beat";private var snare:ShortArray?=null;private var kick:ShortArray?=null
 override fun onCreate(b:Bundle?){super.onCreate(b);snare=raw(R.raw.battlecat_snare_tight);kick=raw(R.raw.battlecat_kick_dirty)
  val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(38,50,38,25);setBackgroundColor(0xff090b10.toInt())};fun t(x:String,z:Float)=TextView(this).apply{text=x;textSize=z;setTextColor(0xfff4f4f4.toInt());setPadding(0,8,0,8)}
  root.addView(t("HMG // COMPOSER",26f));root.addView(t("Phrase-based instrumental generator • v0.4",14f));val p=EditText(this).apply{hint="dark 90s west coast, sinister minor piano, funky bass, hard drums, dramatic hook";minLines=4;setTextColor(0xffffffff.toInt());setHintTextColor(0xff777b85.toInt())};root.addView(p)
  val bl=t("BPM 88",16f);root.addView(bl);val bpm=SeekBar(this).apply{max=100;progress=28};root.addView(bpm);bpm.setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(s:SeekBar?,v:Int,f:Boolean){bl.text="BPM ${60+v}"};override fun onStartTrackingTouch(s:SeekBar?){};override fun onStopTrackingTouch(s:SeekBar?){}})
  val status=t("Ready",13f);root.addView(status);val gen=Button(this).apply{text="COMPOSE BEAT"};val play=Button(this).apply{text="PLAY / STOP";isEnabled=false};val save=Button(this).apply{text="DOWNLOAD WAV";isEnabled=false};root.addView(gen);root.addView(play);root.addView(save);setContentView(root)
  gen.setOnClickListener{val q=p.text.toString().ifBlank{"dark boom bap minor piano"};promptName=q;gen.isEnabled=false;status.text="Writing harmony, motif, bassline & arrangement...";thread{val a=Composer.render(60+bpm.progress,q,kick,snare);runOnUiThread{pcm=a;status.text="Composed • ${Composer.summary(q)}";gen.isEnabled=true;play.isEnabled=true;save.isEnabled=true}}}
  play.setOnClickListener{if(track?.playState==AudioTrack.PLAYSTATE_PLAYING){track?.stop();track?.release();track=null}else pcm?.let{d->track=AudioTrack.Builder().setAudioAttributes(AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_MEDIA).build()).setAudioFormat(AudioFormat.Builder().setEncoding(AudioFormat.ENCODING_PCM_16BIT).setSampleRate(44100).setChannelMask(AudioFormat.CHANNEL_OUT_STEREO).build()).setBufferSizeInBytes(d.size*2).setTransferMode(AudioTrack.MODE_STATIC).build();track!!.write(d,0,d.size);track!!.play()}}
  save.setOnClickListener{pcm?.let{d->val n="HMG_${promptName.replace(Regex("[^A-Za-z0-9]+"),"_").take(20)}.wav";val v=ContentValues().apply{put(MediaStore.Audio.Media.DISPLAY_NAME,n);put(MediaStore.Audio.Media.MIME_TYPE,"audio/wav");put(MediaStore.Audio.Media.RELATIVE_PATH,"Music/HMG Beat Generator")};contentResolver.insert(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,v)?.let{u->contentResolver.openOutputStream(u)!!.use{stream->Wav.write(stream,d)};status.text="Saved • Music/HMG Beat Generator/$n"}}}
 }
 private fun raw(id:Int)=try{val a=resources.openRawResource(id).readBytes();val b=ByteBuffer.wrap(a,44,a.size-44).order(ByteOrder.LITTLE_ENDIAN);ShortArray((a.size-44)/2){b.short}}catch(e:Exception){null}
}

data class Plan(val west:Boolean,val trap:Boolean,val boom:Boolean,val dark:Boolean,val sparse:Boolean,val dramatic:Boolean,val instrument:String,val progression:IntArray,val scale:IntArray,val root:Double,val motif:IntArray)
object Composer{
 const val SR=44100
 fun plan(p:String):Plan{val s=p.lowercase();fun h(vararg w:String)=w.any{s.contains(it)};val west=h("west coast","g-funk","funk");val trap=h("trap","drill");val boom=h("boom bap","boombap","90s","grimy");val dark=h("dark","sinister","ominous","horror","creepy");val minor=!h("happy","bright","major");val scale=if(minor)intArrayOf(0,3,5,7,10,12) else intArrayOf(0,2,4,7,9,12);val prog=when{dark->intArrayOf(0,5,3,7);west->intArrayOf(0,7,5,3);else->intArrayOf(0,5,7,3)};val inst=when{h("piano","keys")->"piano";h("bell","chime")->"bell";h("organ")->"organ";h("string","orchestral")->"strings";h("synth","g-funk")->"synth";dark->"bell";else->"piano"};val motif=if(h("sparse","minimal"))intArrayOf(0,-1,2,-1,1,-1,3,-1) else if(west)intArrayOf(0,2,3,2,4,3,2,1) else intArrayOf(0,2,1,3,2,4,3,1);return Plan(west,trap,boom,dark,h("sparse","minimal"),h("dramatic","huge","big hook"),inst,prog,scale,if(dark)46.25 else if(west)55.0 else 49.0,motif)}
 fun summary(p:String):String{val x=plan(p);val genre=if(x.west)"West Coast" else if(x.trap)"Trap" else if(x.boom)"Boom-bap" else "Hip-hop";return "$genre • ${x.instrument} • structured hook"}
 fun render(bpm:Int,prompt:String,kickS:ShortArray?,snareS:ShortArray?):ShortArray{val x=plan(prompt);val beat=60.0/bpm;val step=beat/4;val bars=32;val frames=(bars*4*beat*SR).toInt();val l=DoubleArray(frames);val r=DoubleArray(frames);for(bar in 0 until bars){val sec=section(bar);val hook=sec==2||sec==4;val active=sec!=0||bar>=2;val chord=x.progression[(bar/2)%x.progression.size];val chordRoot=x.root*2.0.pow(chord.toDouble()/12.0);if(active)drums(l,r,bar,beat,step,x,hook,kickS,snareS);if(sec!=0||bar>=1){chord(l,r,bar*4*beat,chordRoot,beat*3.7,x.instrument,if(hook) .15 else .10);bassPhrase(l,r,bar,beat,chordRoot,x,hook)};if(bar>=2){melodyPhrase(l,r,bar,beat,step,chordRoot,x,hook);if(hook&&x.dramatic)counter(l,r,bar,beat,chordRoot,x)}};val pk=max(l.maxOf{abs(it)},r.maxOf{abs(it)}).coerceAtLeast(.1);val out=ShortArray(frames*2);for(i in 0 until frames){out[i*2]=(tanh(l[i]/pk*2.2)*30000).toInt().toShort();out[i*2+1]=(tanh(r[i]/pk*2.2)*30000).toInt().toShort()};return out}
 private fun section(b:Int)=when(b){in 0..3->0;in 4..11->1;in 12..15->2;in 16..23->3;in 24..27->4;else->5}
 private fun drums(l:DoubleArray,r:DoubleArray,bar:Int,beat:Double,step:Double,x:Plan,hook:Boolean,k:ShortArray?,s:ShortArray?){val kp=when{x.trap->intArrayOf(0,3,7,10,14);x.west->intArrayOf(0,6,10,14);x.boom->intArrayOf(0,6,9,14);else->intArrayOf(0,7,11,14)};for(pos in 0..15){val swing=if(x.boom&&pos%2==1)step*.12 else 0.0;val t=bar*4*beat+pos*step+swing;if(pos in kp&&(hook||pos!=14||bar%2==1)){if(k!=null)sample(l,r,t,k,.72)else kick(l,r,t,.8)};val sn=if(x.trap)pos==8 else pos==4||pos==12;if(sn){if(s!=null)sample(l,r,t,s,.65)else noise(l,r,t,.45)};val hs=if(x.trap||hook)2 else 4;if(pos%hs==0){val pan=if(pos%4==0)-.2 else .2;hat(l,r,t,.10,pan)}};if(bar%4==3&&hook)noise(l,r,bar*4*beat+15*step,.22)}
 private fun bassPhrase(l:DoubleArray,r:DoubleArray,bar:Int,beat:Double,f:Double,x:Plan,hook:Boolean){val rhythm=if(x.west)doubleArrayOf(0.0,.75,1.5,2.75,3.25) else if(x.trap)doubleArrayOf(0.0,1.5,2.0,3.25) else doubleArrayOf(0.0,1.0,2.5,3.0);for((j,b) in rhythm.withIndex()){val ff=if(j==rhythm.lastIndex&&bar%2==1)f*2.0.pow(7.0/12.0) else f/2.0;val duration=beat*(if(x.trap) .7 else .42);val gain=if(hook) .38 else .29;bass(l,r,(bar*4.0+b)*beat,ff,duration,gain)}}
 private fun melodyPhrase(l:DoubleArray,r:DoubleArray,bar:Int,beat:Double,step:Double,f:Double,x:Plan,hook:Boolean){for(i in x.motif.indices){val degree=x.motif[i];if(degree<0)continue;if(!hook&&x.sparse&&i%2==1)continue;val sem=x.scale[degree%x.scale.size];val octave=if(hook&&i>=4)2.0 else 1.0;val note=f*4.0*octave*2.0.pow(sem.toDouble()/12.0);val duration=step*(if(x.instrument=="strings")5.0 else 1.7);val gain=if(hook) .12 else .075;val pan=if(i%2==0)-.32 else .32;tone(l,r,bar*4*beat+i*step*2,note,duration,gain,x.instrument,pan)}}
 private fun counter(l:DoubleArray,r:DoubleArray,bar:Int,beat:Double,f:Double,x:Plan){for(i in 0..3){val sem=x.scale[(4-i)%x.scale.size];val pan=if(i%2==0).55 else -.55;tone(l,r,(bar*4+i+.5)*beat,f*8.0*2.0.pow(sem.toDouble()/12.0),beat*.35,.055,"synth",pan)}}
 private fun chord(l:DoubleArray,r:DoubleArray,t:Double,f:Double,d:Double,type:String,g:Double){for(semi in intArrayOf(0,3,7)){tone(l,r,t,f*4.0*2.0.pow(semi.toDouble()/12.0),d,g/3.0,type,(semi-3)*.08)}}
 private fun add(l:DoubleArray,r:DoubleArray,i:Int,v:Double,p:Double){if(i !in l.indices)return;l[i]+=v*(1-p)*.5;r[i]+=v*(1+p)*.5}
 private fun sample(l:DoubleArray,r:DoubleArray,t:Double,s:ShortArray,g:Double){var j=0;var i=(t*SR).toInt();while(j+1<s.size&&i<l.size){l[i]+=s[j]/32768.0*g;r[i]+=s[j+1]/32768.0*g;j+=2;i++}}
 private fun kick(l:DoubleArray,r:DoubleArray,t:Double,g:Double){val st=(t*SR).toInt();for(i in 0 until (.35*SR).toInt()){val q=i.toDouble()/SR;add(l,r,st+i,sin(2*PI*(140*exp(-q*18)+44)*q)*exp(-q*12)*g,0.0)}}
 private fun noise(l:DoubleArray,r:DoubleArray,t:Double,g:Double){val st=(t*SR).toInt();var seed=st;for(i in 0 until (.13*SR).toInt()){seed=seed*1664525+1013904223;val v=((seed ushr 16 and 65535)/32768.0-1)*exp(-i.toDouble()/SR*28)*g;add(l,r,st+i,v,0.0)}}
 private fun hat(l:DoubleArray,r:DoubleArray,t:Double,g:Double,p:Double){val st=(t*SR).toInt();var seed=st+9;for(i in 0 until (.045*SR).toInt()){seed=seed*1103515245+12345;val v=((seed ushr 16 and 65535)/32768.0-1)*exp(-i.toDouble()/SR*95)*g;add(l,r,st+i,v,p)}}
 private fun bass(l:DoubleArray,r:DoubleArray,t:Double,f:Double,d:Double,g:Double){val st=(t*SR).toInt();for(i in 0 until (d*SR).toInt()){val q=i.toDouble()/SR;add(l,r,st+i,(sin(2*PI*f*q)+.18*sin(4*PI*f*q))*exp(-q*2.2)*g,0.0)}}
 private fun tone(l:DoubleArray,r:DoubleArray,t:Double,f:Double,d:Double,g:Double,type:String,p:Double){val st=(t*SR).toInt();for(i in 0 until (d*SR).toInt()){val q=i.toDouble()/SR;val e=(1-exp(-q*30))*exp(-q*(if(type=="strings")1.1 else 3.8));val v=when(type){"bell"->sin(2*PI*f*q)+.35*sin(2*PI*f*2.01*q)+.15*sin(2*PI*f*3.98*q);"organ"->sin(2*PI*f*q)+.3*sin(4*PI*f*q);"synth"->sin(2*PI*f*q)+.22*sin(6*PI*f*q);"strings"->sin(2*PI*f*q)+.25*sin(2*PI*f*1.006*q);else->sin(2*PI*f*q)+.12*sin(4*PI*f*q)};add(l,r,st+i,v*e*g,p)}}
}
object Wav{fun write(o:OutputStream,d:ShortArray){val n=d.size*2;fun le(v:Int,c:Int){repeat(c){o.write(v shr (8*it) and 255)}};o.write("RIFF".toByteArray());le(36+n,4);o.write("WAVEfmt ".toByteArray());le(16,4);le(1,2);le(2,2);le(44100,4);le(176400,4);le(4,2);le(16,2);o.write("data".toByteArray());le(n,4);for(x in d){val v=x.toInt();o.write(v and 255);o.write(v shr 8 and 255)}}}